name: The Full Workflow (Unit Test - Coverage - Image Building)
on:
    workflow_dispatch:
    push:
        branches:
            - feature-branchA
            - main

env:
    MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit_testing:
        name: unit testing
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node-version: [18, 19, 20]
                exclude:
                    - os: macos-latest
                      node-version: 18
        runs-on: ${{ matrix.os }}
        # runs-on: self-hosted
        steps:
            - name: runner info
              run: echo "Running on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"

            - name: Checkout
              uses: actions/checkout@v5
            
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.4.0
              with:
                node-version: ${{ matrix.node-version }}
            
            - name: install dependencies
              run: npm install

            - name: Run tests
              run: npm test
    
    code_coverage:
        runs-on: ubuntu-latest
        # runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.4.0
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Generate coverage report
              run: npm run coverage

            - name: Upload coverage report
              uses: actions/upload-artifact@v4.6.2
              with:
                  name: coverage-report
                  path: ./coverage/

    image_building:
        needs: [unit_testing, code_coverage]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PATOKEN }}

            - name: Build Docker Image
              run: docker build -t sotirusama/solar-system:${{ github.sha }} .

            - name: Tag Docker Image
              run: docker tag sotirusama/solar-system:${{ github.sha }} sotirusama/solar-system:latest

            - name: Push Docker Image
              run: docker push sotirusama/solar-system:latest